---
- name: Perform tasks on servers
  hosts: all
  tasks:
    - name: Ping servers and save results
      ping:
      register: ping_result

    - name: Save ping results to ping-output.txt
      copy:
        content: "{{ ping_result }}"
        dest: ping-output.txt
      delegate_to: localhost
      run_once: yes

    - name: Copy httpd.conf to /tmp/
      copy:
        src: /home/httpd.conf
        dest: /tmp/
      tags: push

    - name: Set variable for .99 server
      set_fact:
        stype: jump
      when: inventory_hostname in groups['rae']

    - name: Set variable for 127.0.0.1 server
      set_fact:
        stype: local
      when: inventory_hostname in groups['localhosts']

    - name: Print stype variable for each node
      debug:
        msg: "stype for {{ inventory_hostname }} is {{ hostvars[inventory_hostname]['stype'] }}"

    - name: Tar /tmp/ directory when stype=service
      command: tar -czf /tmp/archive.tar.gz /tmp/
      when: stype == 'service'
